// Pairwise vector-similarity scan that files `duplicate` suggestions for
// record pairs above a cosine-similarity threshold. Run on demand via
// `POST /maintenance/find-duplicates` or as a scheduled maintenance job.
//
// Per design constraint C16: this is deterministic work (vector math), so
// it lives in the indexer / maintenance layer, not in an agent. The agent
// reviews the filed suggestions via `/vault-review-duplicates` and decides:
// merge the two notes, keep both as related-to, treat as contradiction
// (file `contradiction_candidate`), or reject the suggestion.
//
// **Distance metric: min cosine over chunk pairs**, not whole-document
// (mean-pooled) cosine. Mean-pool produced a centroid-of-everything for
// long heterogeneous notes — `projects/vault-storage/queue.md` was
// `a_record` on 39 of 144 false-positive pairings on the 2026-05-03 run
// against unrelated topics, because its mean-pool vector landed near the
// centroid of the topic cloud.  The chunk-level scan (`RecordVecRepository.
// nearestToRecord`) takes the closest chunk-pair distance per target
// record, which surfaces real concept overlap and ignores the long-doc
// average. Swap shipped 2026-05-03; rationale tracked at
// `[[projects/vault-storage/queue]]` § "Whole-doc embedding smear".
//
// Idempotency: a `duplicate` suggestion of any status for the same
// unordered pair blocks re-filing, so re-running the scan is cheap and
// only adds new pairs the previous scan didn't have data for (e.g.,
// records added since).

import type {DatabaseSync} from 'node:sqlite';
import {RecordVecRepository} from '../db/vec-repo.ts';
import {DuplicateSuggestionFiler} from '../importer/file-suggestions.ts';
import {RecordsRepository} from '../records/repository.ts';
import type {RecordType, VaultRecord} from '../records/types.ts';

/**
 * Default record types the scan ignores. `state` is autogenerated boilerplate
 * (per the vault-check-drift skill) — multiple project state.md files share
 * identical content and aren't conceptual duplicates. `meta` is `_about.md`
 * and similar non-knowledge records.
 */
export const DEFAULT_SKIP_TYPES: readonly RecordType[] = ['state', 'meta'];

/**
 * Default file_path prefixes the scan ignores. `logs/sync/` is mechanical
 * sync-pass output; identical-body pairs there are "no changes both times",
 * not duplicates of substance.
 */
export const DEFAULT_SKIP_PATH_PREFIXES: readonly string[] = ['logs/sync/'];

export interface FindDuplicatesOptions {
  /**
   * Cosine distance ceiling. Pairs with `distance ≤ maxDistance` are filed.
   * Default 0.10 (≥ 0.90 cosine similarity). Tighten (lower) to reduce queue
   * size; loosen (higher) to surface more potential merges at the cost of
   * agent review time.
   */
  maxDistance?: number;
  /** Per-record neighbor breadth fed into the vector index. Default 10. */
  perRecord?: number;
  /** Maximum suggestions filed in this pass; remaining pairs are deferred. */
  limit?: number;
  /**
   * Skip records whose body is shorter than this many characters. Defaults to
   * 200 — short bodies don't carry enough signal for "duplicate" to be
   * meaningful (e.g., empty queue.md files share identical boilerplate).
   */
  minBodyLength?: number;
  /** Skip records of these types. Default `DEFAULT_SKIP_TYPES`. */
  skipTypes?: readonly RecordType[];
  /** Skip records whose file_path starts with any of these. Default `DEFAULT_SKIP_PATH_PREFIXES`. */
  skipPathPrefixes?: readonly string[];
  /** Override the timestamp written to suggestion rows (test injection). */
  now?: string;
}

export interface FindDuplicatesSummary {
  /** Records scanned (had embeddings + survived all filters). */
  scanned: number;
  /** Records skipped because they have no embedding yet. */
  skippedUnembedded: number;
  /** Records skipped because their body was below `minBodyLength`. */
  skippedShort: number;
  /** Records skipped because of `skipTypes` membership. */
  skippedByType: number;
  /** Records skipped because of `skipPathPrefixes` match. */
  skippedByPath: number;
  /** Unique pairs above threshold encountered (post-canonicalization, post-filter). */
  pairsFound: number;
  /** New `duplicate` suggestions filed. Pre-existing pairs do not refile. */
  filed: number;
  durationMs: number;
}

/**
 * Scan all embedded records for high-similarity pairs and file
 * `duplicate` suggestions. Pairs are unordered: a record's nearest
 * neighbour gets canonicalized to `(min, max)` before lookup, so each pair
 * is considered exactly once per pass.
 */
export const findDuplicates = (
  db: DatabaseSync,
  options: FindDuplicatesOptions = {}
): FindDuplicatesSummary => {
  const maxDistance = options.maxDistance ?? 0.1;
  const perRecord = options.perRecord ?? 10;
  const limit = options.limit;
  const minBodyLength = options.minBodyLength ?? 200;
  const skipTypes = new Set<string>(options.skipTypes ?? DEFAULT_SKIP_TYPES);
  const skipPathPrefixes = options.skipPathPrefixes ?? DEFAULT_SKIP_PATH_PREFIXES;
  const now = options.now ?? new Date().toISOString();

  const records = new RecordsRepository(db);
  const vec = new RecordVecRepository(db);
  const filer = new DuplicateSuggestionFiler(db);

  const all = records.listAll();
  const byId = new Map<string, VaultRecord>();
  for (const r of all) byId.set(r.recordId, r);

  const summary: FindDuplicatesSummary = {
    scanned: 0,
    skippedUnembedded: 0,
    skippedShort: 0,
    skippedByType: 0,
    skippedByPath: 0,
    pairsFound: 0,
    filed: 0,
    durationMs: 0
  };
  const start = performance.now();
  const seenPairs = new Set<string>();

  // Returns true when the record should NOT participate in the scan as either
  // outer or inner side. Counters distinguish causes for observability.
  const shouldSkip = (
    r: VaultRecord
  ): {skip: boolean; reason: 'short' | 'type' | 'path' | null} => {
    if (skipTypes.has(r.type)) return {skip: true, reason: 'type'};
    if (skipPathPrefixes.some(p => r.filePath.startsWith(p))) return {skip: true, reason: 'path'};
    if (r.body.length < minBodyLength) return {skip: true, reason: 'short'};
    return {skip: false, reason: null};
  };

  for (const r of all) {
    if (limit !== undefined && summary.filed >= limit) break;
    if (!vec.hasRecord(r.recordId)) {
      summary.skippedUnembedded++;
      continue;
    }
    const outer = shouldSkip(r);
    if (outer.skip) {
      if (outer.reason === 'short') summary.skippedShort++;
      else if (outer.reason === 'type') summary.skippedByType++;
      else if (outer.reason === 'path') summary.skippedByPath++;
      continue;
    }
    summary.scanned++;
    const neighbors = vec.nearestToRecord(r.recordId, perRecord);
    for (const n of neighbors) {
      // Defensive guard: a non-finite distance means at least one of the two
      // doc vectors had non-finite components (the embedder produced a NaN
      // chunk for one of them and the mean-pool filter did not catch it —
      // see `meanPoolNormalize`). Don't file a suggestion the agent can't
      // rank or auto-threshold; let the next embed pass produce a clean
      // doc-vec and the next scan refile the pair with a real distance.
      if (!Number.isFinite(n.distance)) continue;
      if (n.distance > maxDistance) break; // results are sorted ascending by distance
      const nRec = byId.get(n.recordId);
      if (!nRec) continue;
      // Inner-side filter: skip neighbours that are themselves boilerplate /
      // skipped types / skipped paths. Don't bump counters here — outer-side
      // already counted them when they were the outer record.
      if (shouldSkip(nRec).skip) continue;
      const [aId, bId] =
        r.recordId < n.recordId ? [r.recordId, n.recordId] : [n.recordId, r.recordId];
      const key = `${aId}|${bId}`;
      if (seenPairs.has(key)) continue;
      seenPairs.add(key);
      summary.pairsFound++;
      if (limit !== undefined && summary.filed >= limit) break;
      const aRec = byId.get(aId);
      const bRec = byId.get(bId);
      if (!aRec || !bRec) continue;
      const filed = filer.fileDuplicateSuggestion({
        aRecordId: aId,
        aPath: aRec.filePath,
        bRecordId: bId,
        bPath: bRec.filePath,
        distance: n.distance,
        now
      });
      if (filed) summary.filed++;
    }
  }

  summary.durationMs = Math.round(performance.now() - start);
  return summary;
};
