// Pairwise vector-similarity scan that files `duplicate` suggestions for
// record pairs above a cosine-similarity threshold. Run on demand via
// `POST /maintenance/find-duplicates` or as a scheduled maintenance job.
//
// Per design constraint C16: this is deterministic work (vector math), so
// it lives in the indexer / maintenance layer, not in an agent. The agent
// reviews the filed suggestions via `/vault-review-duplicates` and decides:
// merge the two notes, keep both as related-to, treat as contradiction
// (file `contradiction_candidate`), or reject the suggestion.
//
// **Two-phase scan** — doc-level mean-pool prefilter (cheap, wide-cutoff
// exclusion only) → chunk-level pairwise min-cosine confirms each
// candidate at the precise threshold. Restored sub-second latency after
// the 2026-05-03 single-phase chunk-level swap pushed live-vault scans
// to ~100s (768 records × ~7 chunks × 50-NN-each = ~270 K sqlite-vec
// queries).
//
// Why two phases:
//   - Doc-level mean-pool alone smears centroids on long heterogeneous
//     notes (queue.md was paired with 39 unrelated topics on the
//     2026-05-03 dashboard run). The 2026-05-03 first fix swapped
//     entirely to chunk-level — correct metric, wrong latency.
//   - Chunk-level alone is precise but ~270 K vec queries on the live
//     vault. ~100 s.
//   - Combine: doc-level as a coarse *exclusion* filter (centroid >
//     prefilterMaxDistance ⇒ no chunk pair can be close — the centroids
//     bound the chunk-pair distance from below by the triangle
//     inequality with margin set to the prefilter threshold).
//     Chunk-level confirms only the survivors at the precise
//     `maxDistance`. Centroid smear can no longer pick false positives
//     because chunk-level always has the final say.
//
// Pairwise chunk-min is computed in JS over already-loaded float arrays
// (cosine = 1 - dot since vectors are L2-normalized at write time). For
// typical 5–20 chunks per record the per-pair cost is ~10–500 µs.
//
// Idempotency: a `duplicate` suggestion of any status for the same
// unordered pair blocks re-filing, so re-running the scan is cheap and
// only adds new pairs the previous scan didn't have data for (e.g.,
// records added since).

import type {DatabaseSync} from 'node:sqlite';
import {RecordDocVecRepository} from '../db/doc-vec-repo.ts';
import {RecordVecRepository} from '../db/vec-repo.ts';
import {DuplicateSuggestionFiler} from '../importer/file-suggestions.ts';
import {RecordsRepository} from '../records/repository.ts';
import type {RecordType, VaultRecord} from '../records/types.ts';

/**
 * Default record types the scan ignores. `state` is autogenerated boilerplate
 * (per the vault-check-drift skill) — multiple project state.md files share
 * identical content and aren't conceptual duplicates. `meta` is `_about.md`
 * and similar non-knowledge records.
 */
export const DEFAULT_SKIP_TYPES: readonly RecordType[] = ['state', 'meta'];

/**
 * Default file_path prefixes the scan ignores. `logs/sync/` is mechanical
 * sync-pass output; identical-body pairs there are "no changes both times",
 * not duplicates of substance.
 */
export const DEFAULT_SKIP_PATH_PREFIXES: readonly string[] = ['logs/sync/'];

export interface FindDuplicatesOptions {
  /**
   * Cosine distance ceiling for the **chunk-level** confirmation phase.
   * Pairs whose min chunk-pair distance ≤ maxDistance are filed. Default
   * 0.10 (≥ 0.90 cosine similarity).
   */
  maxDistance?: number;
  /**
   * Cosine distance ceiling for the **doc-level prefilter** phase. Pairs
   * whose mean-pool centroid distance > prefilterMaxDistance are excluded
   * before any chunk-level work. Default 0.30 — wide enough that any pair
   * whose chunks have meaningful overlap will pass through, narrow enough
   * to drop the obvious-orthogonal mass that dominates at scale. Set
   * higher if you suspect a pair with very long heterogeneous content
   * is being missed; set lower for faster but less-thorough scans.
   */
  prefilterMaxDistance?: number;
  /**
   * Per-record neighbor breadth fed into the doc-level prefilter. Default
   * 20. Tighter than the prior chunk-level scan's 10 because doc-level
   * NN sometimes ranks centroid-close-but-conceptually-distinct pairs
   * ahead of true near-duplicates; we widen to make sure the chunk-level
   * confirmation phase sees real candidates.
   */
  perRecord?: number;
  /** Maximum suggestions filed in this pass; remaining pairs are deferred. */
  limit?: number;
  /**
   * Skip records whose body is shorter than this many characters. Defaults to
   * 200 — short bodies don't carry enough signal for "duplicate" to be
   * meaningful (e.g., empty queue.md files share identical boilerplate).
   */
  minBodyLength?: number;
  /** Skip records of these types. Default `DEFAULT_SKIP_TYPES`. */
  skipTypes?: readonly RecordType[];
  /** Skip records whose file_path starts with any of these. Default `DEFAULT_SKIP_PATH_PREFIXES`. */
  skipPathPrefixes?: readonly string[];
  /** Override the timestamp written to suggestion rows (test injection). */
  now?: string;
}

export interface FindDuplicatesSummary {
  /** Records scanned (had embeddings + survived all filters). */
  scanned: number;
  /** Records skipped because they have no embedding yet. */
  skippedUnembedded: number;
  /** Records skipped because their body was below `minBodyLength`. */
  skippedShort: number;
  /** Records skipped because of `skipTypes` membership. */
  skippedByType: number;
  /** Records skipped because of `skipPathPrefixes` match. */
  skippedByPath: number;
  /** Pairs surviving the doc-level prefilter (centroid distance ≤ prefilterMaxDistance). */
  candidatePairs: number;
  /** Unique pairs above threshold encountered (post-canonicalization, post-filter, post-chunk-confirm). */
  pairsFound: number;
  /** New `duplicate` suggestions filed. Pre-existing pairs do not refile. */
  filed: number;
  durationMs: number;
}

/**
 * Pairwise min cosine distance between two records' chunk vectors.
 * Both arrays must hold L2-normalized vectors of the same dimension
 * (sqlite-vec normalizes at write time, so any chunks loaded via
 * `RecordVecRepository.getChunks` already satisfy that invariant).
 *
 * Returns the smallest `1 - dot(a_i, b_j)` across the cartesian product,
 * which is exactly the "best matching chunk wins" semantic that the
 * old chunk-level scan computed via per-chunk sqlite-vec NN queries —
 * but in pure JS over already-loaded arrays, so it's ~10–500 µs per
 * pair instead of ~10–30 ms per chunk-NN-query × every chunk.
 *
 * Returns `Infinity` when either side has no chunks.
 */
const minPairwiseChunkDistance = (
  a: readonly Float32Array[],
  b: readonly Float32Array[]
): number => {
  if (a.length === 0 || b.length === 0) return Infinity;
  const dim = a[0]!.length;
  let bestDot = -Infinity;
  for (const av of a) {
    for (const bv of b) {
      let dot = 0;
      for (let i = 0; i < dim; ++i) dot += av[i]! * bv[i]!;
      if (dot > bestDot) bestDot = dot;
    }
  }
  return 1 - bestDot;
};

/**
 * Scan all embedded records for high-similarity pairs and file
 * `duplicate` suggestions. Two-phase: doc-level prefilter for cheap
 * exclusion, chunk-level pairwise min cosine for precise inclusion.
 * Pairs are unordered: a record's nearest neighbour gets canonicalized
 * to `(min, max)` before lookup, so each pair is considered exactly
 * once per pass.
 */
export const findDuplicates = (
  db: DatabaseSync,
  options: FindDuplicatesOptions = {}
): FindDuplicatesSummary => {
  const maxDistance = options.maxDistance ?? 0.1;
  const prefilterMaxDistance = options.prefilterMaxDistance ?? 0.3;
  const perRecord = options.perRecord ?? 20;
  const limit = options.limit;
  const minBodyLength = options.minBodyLength ?? 200;
  const skipTypes = new Set<string>(options.skipTypes ?? DEFAULT_SKIP_TYPES);
  const skipPathPrefixes = options.skipPathPrefixes ?? DEFAULT_SKIP_PATH_PREFIXES;
  const now = options.now ?? new Date().toISOString();

  const records = new RecordsRepository(db);
  const docVecs = new RecordDocVecRepository(db);
  const chunkVecs = new RecordVecRepository(db);
  const filer = new DuplicateSuggestionFiler(db);

  const all = records.listAll();
  const byId = new Map<string, VaultRecord>();
  for (const r of all) byId.set(r.recordId, r);

  const summary: FindDuplicatesSummary = {
    scanned: 0,
    skippedUnembedded: 0,
    skippedShort: 0,
    skippedByType: 0,
    skippedByPath: 0,
    candidatePairs: 0,
    pairsFound: 0,
    filed: 0,
    durationMs: 0
  };
  const start = performance.now();
  const seenPairs = new Set<string>();

  // Bulk-load every record's chunks in a single record_vec scan. Per-call
  // `getChunks(recordId)` would issue one full vec0 scan each time —
  // record_vec's `+record_id` aux column is unindexed, so a `WHERE
  // record_id = ?` query has no early exit, and at ~6K chunks costs ~20ms
  // regardless of how many chunks the record actually has. Profiled
  // 2026-05-04: ~150 unique records × ~22ms ≈ 3.3s of pure overhead,
  // ~80% of the find-duplicates wall time. One bulk scan is ~50–150ms
  // and gives O(1) lookups for the rest of the pass. Lifetime: one scan.
  const allChunks = chunkVecs.getAllChunks();
  const getChunks = (recordId: string): Float32Array[] => allChunks.get(recordId) ?? [];

  // Returns true when the record should NOT participate in the scan as either
  // outer or inner side. Counters distinguish causes for observability.
  const shouldSkip = (
    r: VaultRecord
  ): {skip: boolean; reason: 'short' | 'type' | 'path' | null} => {
    if (skipTypes.has(r.type)) return {skip: true, reason: 'type'};
    if (skipPathPrefixes.some(p => r.filePath.startsWith(p))) return {skip: true, reason: 'path'};
    if (r.body.length < minBodyLength) return {skip: true, reason: 'short'};
    return {skip: false, reason: null};
  };

  for (const r of all) {
    if (limit !== undefined && summary.filed >= limit) break;
    if (!docVecs.hasRecord(r.recordId)) {
      summary.skippedUnembedded++;
      continue;
    }
    const outer = shouldSkip(r);
    if (outer.skip) {
      if (outer.reason === 'short') summary.skippedShort++;
      else if (outer.reason === 'type') summary.skippedByType++;
      else if (outer.reason === 'path') summary.skippedByPath++;
      continue;
    }
    summary.scanned++;

    // Phase 1: doc-level prefilter — fast top-K with mean-pool centroid.
    const candidates = docVecs.nearestToRecord(r.recordId, perRecord);
    for (const cand of candidates) {
      // Defensive: a non-finite doc-distance means a NaN chunk poisoned
      // one of the centroids (the embedder produced a non-finite vector
      // and the mean-pool filter didn't catch it). Skip — phase-2
      // chunk-level may still surface the pair on the next clean
      // re-embed pass.
      if (!Number.isFinite(cand.distance)) continue;
      // Sorted ascending by doc-distance; once we cross the prefilter
      // ceiling, no further candidate is closer.
      if (cand.distance > prefilterMaxDistance) break;

      const nRec = byId.get(cand.recordId);
      if (!nRec) continue;
      // Inner-side filter — skip boilerplate / skipped types / skipped
      // paths on the candidate without bumping counters (outer-side
      // already counted them when they were outer records).
      if (shouldSkip(nRec).skip) continue;

      const [aId, bId] =
        r.recordId < cand.recordId ? [r.recordId, cand.recordId] : [cand.recordId, r.recordId];
      const key = `${aId}|${bId}`;
      if (seenPairs.has(key)) continue;
      seenPairs.add(key);
      ++summary.candidatePairs;

      // Phase 2: chunk-level pairwise min cosine — precise threshold.
      const aChunks = getChunks(aId);
      const bChunks = getChunks(bId);
      const distance = minPairwiseChunkDistance(aChunks, bChunks);
      if (!Number.isFinite(distance)) continue; // unembedded → infinity
      if (distance > maxDistance) continue;

      summary.pairsFound++;
      if (limit !== undefined && summary.filed >= limit) break;
      const aRec = byId.get(aId);
      const bRec = byId.get(bId);
      if (!aRec || !bRec) continue;
      const filed = filer.fileDuplicateSuggestion({
        aRecordId: aId,
        aPath: aRec.filePath,
        bRecordId: bId,
        bPath: bRec.filePath,
        distance,
        now
      });
      if (filed) summary.filed++;
    }
  }

  summary.durationMs = Math.round(performance.now() - start);
  return summary;
};
